.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PAGERUNIT" "7" "July 2011" "" "PagerUnit"
.
.SH "NAME"
\fBpagerunit\fR \- a simple Nagios alternative made to look like unit tests
.
.SH "SYNOPSIS"
.
.SH "DESCRIPTION"
.
.SH "OPTIONS"
.
.SH "FILES"
.
.TP
\fB/etc/pagerunit\.cfg\fR, \fB~/\.pagerunit\.cfg\fR
PagerUnit\'s configuration file, where mail server information is stored\. See \fBpagerunit\fR(5)\.
.
.SH "THEME SONG"
Beirut \- "Elephant Gun"
.
.SH "AUTHOR"
Richard Crowley \fIr@rcrowley\.org\fR
.
.SH "SEE ALSO"
\fBpagerunit\fR(1) documents the command\-line tool\. \fBpagerunit\fR(5) documents the configuration file format\.
